// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKm3SbfZdHr0pgRAlPHtheUnFYrfQyxC8',
    appId: '1:267165084814:web:113e2ea7dab47639cb2ddf',
    messagingSenderId: '267165084814',
    projectId: 'pbi-time-management',
    authDomain: 'pbi-time-management.firebaseapp.com',
    storageBucket: 'pbi-time-management.firebasestorage.app',
    measurementId: 'G-ZK82L3L2MQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY5LlrZx_JRaOKGmgeVwirfh0DvTOP_Ak',
    appId: '1:267165084814:android:6ecac82388e45dcacb2ddf',
    messagingSenderId: '267165084814',
    projectId: 'pbi-time-management',
    storageBucket: 'pbi-time-management.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2H503Rpuqpt9a2lQaRpunQNx3GuofNNg',
    appId: '1:267165084814:ios:348e644fe22a8fc0cb2ddf',
    messagingSenderId: '267165084814',
    projectId: 'pbi-time-management',
    storageBucket: 'pbi-time-management.firebasestorage.app',
    iosBundleId: 'com.pbi.pbiTime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2H503Rpuqpt9a2lQaRpunQNx3GuofNNg',
    appId: '1:267165084814:ios:348e644fe22a8fc0cb2ddf',
    messagingSenderId: '267165084814',
    projectId: 'pbi-time-management',
    storageBucket: 'pbi-time-management.firebasestorage.app',
    iosBundleId: 'com.pbi.pbiTime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKm3SbfZdHr0pgRAlPHtheUnFYrfQyxC8',
    appId: '1:267165084814:web:1add90c5a7b45cb9cb2ddf',
    messagingSenderId: '267165084814',
    projectId: 'pbi-time-management',
    authDomain: 'pbi-time-management.firebaseapp.com',
    storageBucket: 'pbi-time-management.firebasestorage.app',
    measurementId: 'G-4QWEYSWL7T',
  );
}